// Maps FC26 nationality_name → flagcdn.com ISO code
// Usage: https://flagcdn.com/16x12/{code}.png
export const FLAG_CODES: Record<string, string> = {
  'Afghanistan':             'af',
  'Albania':                 'al',
  'Algeria':                 'dz',
  'Andorra':                 'ad',
  'Angola':                  'ao',
  'Antigua and Barbuda':     'ag',
  'Argentina':               'ar',
  'Armenia':                 'am',
  'Australia':               'au',
  'Austria':                 'at',
  'Azerbaijan':              'az',
  'Bangladesh':              'bd',
  'Barbados':                'bb',
  'Belarus':                 'by',
  'Belgium':                 'be',
  'Benin':                   'bj',
  'Bermuda':                 'bm',
  'Bolivia':                 'bo',
  'Bosnia and Herzegovina':  'ba',
  'Brazil':                  'br',
  'Bulgaria':                'bg',
  'Burkina Faso':            'bf',
  'Burundi':                 'bi',
  'Cabo Verde':              'cv',
  'Cameroon':                'cm',
  'Canada':                  'ca',
  'Central African Republic':'cf',
  'Chad':                    'td',
  'Chile':                   'cl',
  'China PR':                'cn',
  'Chinese Taipei':          'tw',
  'Colombia':                'co',
  'Comoros':                 'km',
  'Congo':                   'cg',
  'Congo DR':                'cd',
  'Costa Rica':              'cr',
  "Côte d'Ivoire":           'ci',
  'Croatia':                 'hr',
  'Cuba':                    'cu',
  'Curacao':                 'cw',
  'Cyprus':                  'cy',
  'Czechia':                 'cz',
  'Denmark':                 'dk',
  'Dominican Republic':      'do',
  'Ecuador':                 'ec',
  'Egypt':                   'eg',
  'El Salvador':             'sv',
  'England':                 'gb-eng',
  'Equatorial Guinea':       'gq',
  'Estonia':                 'ee',
  'Faroe Islands':           'fo',
  'Finland':                 'fi',
  'France':                  'fr',
  'Gabon':                   'ga',
  'Gambia':                  'gm',
  'Georgia':                 'ge',
  'Germany':                 'de',
  'Ghana':                   'gh',
  'Gibraltar':               'gi',
  'Greece':                  'gr',
  'Grenada':                 'gd',
  'Guatemala':               'gt',
  'Guinea':                  'gn',
  'Guinea-Bissau':           'gw',
  'Guyana':                  'gy',
  'Haiti':                   'ht',
  'Honduras':                'hn',
  'Hong Kong':               'hk',
  'Hungary':                 'hu',
  'Iceland':                 'is',
  'India':                   'in',
  'Indonesia':               'id',
  'Iran':                    'ir',
  'Iraq':                    'iq',
  'Israel':                  'il',
  'Italy':                   'it',
  'Jamaica':                 'jm',
  'Japan':                   'jp',
  'Jordan':                  'jo',
  'Kenya':                   'ke',
  'Korea Republic':          'kr',
  'Kosovo':                  'xk',
  'Latvia':                  'lv',
  'Lebanon':                 'lb',
  'Liberia':                 'lr',
  'Libya':                   'ly',
  'Liechtenstein':           'li',
  'Lithuania':               'lt',
  'Luxembourg':              'lu',
  'Madagascar':              'mg',
  'Malawi':                  'mw',
  'Malaysia':                'my',
  'Mali':                    'ml',
  'Malta':                   'mt',
  'Mauritania':              'mr',
  'Mexico':                  'mx',
  'Moldova':                 'md',
  'Montenegro':              'me',
  'Montserrat':              'ms',
  'Morocco':                 'ma',
  'Mozambique':              'mz',
  'Namibia':                 'na',
  'Netherlands':             'nl',
  'New Caledonia':           'nc',
  'New Zealand':             'nz',
  'Niger':                   'ne',
  'Nigeria':                 'ng',
  'North Macedonia':         'mk',
  'Northern Ireland':        'gb-nir',
  'Norway':                  'no',
  'Pakistan':                'pk',
  'Palestine':               'ps',
  'Panama':                  'pa',
  'Paraguay':                'py',
  'Peru':                    'pe',
  'Philippines':             'ph',
  'Poland':                  'pl',
  'Portugal':                'pt',
  'Puerto Rico':             'pr',
  'Qatar':                   'qa',
  'Republic of Ireland':     'ie',
  'Romania':                 'ro',
  'Russia':                  'ru',
  'Rwanda':                  'rw',
  'Saint Kitts and Nevis':   'kn',
  'Saint Lucia':             'lc',
  'Saudi Arabia':            'sa',
  'Scotland':                'gb-sct',
  'Senegal':                 'sn',
  'Serbia':                  'rs',
  'Sierra Leone':            'sl',
  'Slovakia':                'sk',
  'Slovenia':                'si',
  'Somalia':                 'so',
  'South Africa':            'za',
  'Spain':                   'es',
  'Sri Lanka':               'lk',
  'Suriname':                'sr',
  'Sweden':                  'se',
  'Switzerland':             'ch',
  'Syria':                   'sy',
  'Tajikistan':              'tj',
  'Tanzania':                'tz',
  'Thailand':                'th',
  'Togo':                    'tg',
  'Trinidad and Tobago':     'tt',
  'Tunisia':                 'tn',
  'Türkiye':                 'tr',
  'Uganda':                  'ug',
  'Ukraine':                 'ua',
  'United Arab Emirates':    'ae',
  'United States':           'us',
  'Uruguay':                 'uy',
  'Uzbekistan':              'uz',
  'Vanuatu':                 'vu',
  'Venezuela':               've',
  'Wales':                   'gb-wls',
  'Yemen':                   'ye',
  'Zambia':                  'zm',
  'Zimbabwe':                'zw',
}

export function flagUrl(nationality: string | null, size: '16x12' | '20x15' | '32x24' = '20x15'): string | null {
  if (!nationality) return null
  const code = FLAG_CODES[nationality]
  if (!code) return null
  return `https://flagcdn.com/${size}/${code}.png`
}
